version: 2.1

jobs:

  test-python310:
    docker:
      - image: python:3.10-slim
    steps:
      - checkout
      - run:
          command: tests/run_tests.sh -s -vvv
      - store_artifacts:
          path: tests/htmlcov
      - store_artifacts:
          path: tests/coverage.log
      - store_artifacts:
          path: tests/pylint.log

  test-python311:
    docker:
      - image: python:3.11-slim
    steps:
      - checkout
      - run:
          command: tests/run_tests.sh -s -vvv
      - store_artifacts:
          path: tests/htmlcov
      - store_artifacts:
          path: tests/coverage.log
      - store_artifacts:
          path: tests/pylint.log

  publish-to-test-pypi:
    docker:
      - image: python:3.11-slim
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt install -y python3-pip
            pip wheel --no-deps -w dist .
            pip install --upgrade -r dist-requirements.txt
            twine upload \
              --username "__token__" \
              --password "${TESTPYPI_DYNAMIC_VERSIONING_API_TOKEN}" \
              --disable-progress-bar --non-interactive --verbose dist/*

  publish-to-pypi:
    docker:
      - image: python:3.11-slim
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt install -y python3-pip
            pip wheel --no-deps -w dist .
            pip install --upgrade -r dist-requirements.txt
            twine upload \
              --username "__token__" \
              --password "${PYPI_DYNAMIC_VERSIONING_API_TOKEN}" \
              --disable-progress-bar --non-interactive --verbose dist/*

workflows:
  version: 2.1
  main:
    jobs:
      - test-python310
      - test-python311
      - publish-to-pypi:
        requires:
          - test-python310
          - test-python311
          filters:
            branches:
              only:
                - main
      - publish-to-test-pypi:
        requires:
          - test-python310
          - test-python311
          filters:
            branches:
              only:
                - dev
